/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package res.dlt.accumulator

import kotlin.test.Test
import kotlin.test.assertNotNull

class RSAAccumulatorTest {
    @Test fun createRSAAccumulator() {
        val accumulator = RSAAccumulator.newInstance()
        assertNotNull(accumulator.a, "accumulator should have property a")
    }
}
