/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package res.dlt.accumulator

import kotlin.test.Test
import kotlin.test.assertTrue

class RSAAccumulatorTest {
    @Test fun testSomeRSAAccumulatorMethod() {
        val classUnderTest = RSAAccumulator()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
